
extends: 
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:jest/recommended
  - plugin:jest/style
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint/eslint-plugin'
  - jest
rules:
  '@typescript-eslint/naming-convention':
    - error
  '@typescript-eslint/no-unused-vars':
    - warn
    - varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"
      caughtErrorsIgnorePattern: "^_"
      destructuredArrayIgnorePattern: "^_"
  no-console:
    - warn
    - allow: ["warn", "error"]
  eqeqeq:
    - error
  prettier/prettier:
    - error
  jest/consistent-test-it: 
    - error
  jest/require-top-level-describe:
    - error
